version: "3"
services:
  server:
    build: ./server
    container_name: server
    ports:
      - "50051:50051"
    volumes:
      - ./data:/usr/src/data
  client:
    build: ./client
    container_name: client
    pid: host
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/data
      - ./protos:/usr/src/protos