# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: discount_calculator.proto for package 'server'

require 'grpc'
require 'discount_calculator_pb'

module Server
  module DiscountCalculator
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'server.DiscountCalculator'

      rpc :GetDiscount, User, Product
    end

    Stub = Service.rpc_stub_class
  end
end
