# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discount_calculator.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("discount_calculator.proto", :syntax => :proto3) do
    add_message "User" do
      optional :id, :string, 1
      optional :first_name, :string, 2
      optional :last_name, :string, 3
    end
    add_message "Product" do
      optional :id, :string, 1
      optional :price_in_cents, :int32, 2
      optional :title, :string, 3
      optional :description, :string, 4
    end
  end
end

User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("User").msgclass
Product = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Product").msgclass
