# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discount_calculator.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("discount_calculator.proto", :syntax => :proto3) do
    add_message "server.User" do
      optional :id, :string, 1
      optional :first_name, :string, 2
      optional :last_name, :string, 3
    end
    add_message "server.Product" do
      optional :id, :string, 1
      optional :price_in_cents, :int32, 2
      optional :title, :string, 3
      optional :description, :string, 4
    end
  end
end

module Server
  User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("server.User").msgclass
  Product = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("server.Product").msgclass
end
